import { randomUUID } from "node:crypto";
import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { requireStudentSession, StudentSessionRequiredError } from "@/lib/auth/project-session";
import { parseLimitedRequestBody, validateRequestProtocol, validateRequestSource } from "@/lib/auth/route-handler";
import { StudentProjectThreadMoveSchema } from "@/lib/agent/student-project-contract";
import { moveTaskToStudentProject, removeTaskFromStudentProject, StudentProjectConflictError, StudentProjectNotFoundError } from "@/lib/agent/student-project";
import { readEnv } from "@/lib/config/env";
import { createDb, type DatabaseConnection } from "@/lib/db/client";
type Context={params:Promise<{projectId:string}>}; const HEADERS={"Cache-Control":"private, no-store",Vary:"Cookie"};
function fail(error:unknown,requestId:string){if(error instanceof z.ZodError)return NextResponse.json({error:"对话参数无效"},{status:400,headers:HEADERS});if(error instanceof StudentSessionRequiredError)return NextResponse.json({error:error.message},{status:401,headers:HEADERS});if(error instanceof StudentProjectNotFoundError)return NextResponse.json({error:error.message},{status:404,headers:HEADERS});if(error instanceof StudentProjectConflictError)return NextResponse.json({error:error.message},{status:409,headers:HEADERS});console.error({requestId,route:"agent-project-threads",errorName:error instanceof Error?error.name:"UnknownError"});return NextResponse.json({error:"暂时无法更新项目对话"},{status:500,headers:HEADERS});}
export async function POST(request:NextRequest,context:Context){const requestId=randomUUID();let connection:DatabaseConnection|undefined;try{validateRequestProtocol(request);const config=readEnv(process.env);const session=await requireStudentSession(request,config.sessionSecret);const input=await parseLimitedRequestBody(request,StudentProjectThreadMoveSchema,2048);const id=z.string().uuid().parse((await context.params).projectId);connection=createDb(config.databasePath);return NextResponse.json(moveTaskToStudentProject(connection,session,id,input.taskId),{headers:HEADERS});}catch(error){return fail(error,requestId);}finally{connection?.sqlite.close();}}
export async function DELETE(request:NextRequest,context:Context){const requestId=randomUUID();let connection:DatabaseConnection|undefined;try{validateRequestSource(request);const config=readEnv(process.env);const session=await requireStudentSession(request,config.sessionSecret);const id=z.string().uuid().parse((await context.params).projectId);const input=StudentProjectThreadMoveSchema.parse(Object.fromEntries(request.nextUrl.searchParams.entries()));connection=createDb(config.databasePath);return NextResponse.json(removeTaskFromStudentProject(connection,session,id,input.taskId),{headers:HEADERS});}catch(error){return fail(error,requestId);}finally{connection?.sqlite.close();}}
