import type { TouchDesignerFamily } from "@/lib/touchdesigner/types";

type OperatorGlossary = { label: string; description: string };

export const touchDesignerFamilyChinese: Record<TouchDesignerFamily, string> = {
  TOP: "图像",
  CHOP: "通道",
  SOP: "几何",
  COMP: "组件",
  MAT: "材质",
  DAT: "数据",
  POP: "粒子",
  OTHER: "其他",
};

const operatorGlossary: Record<string, OperatorGlossary> = {
  container: { label: "容器组件", description: "封装一组节点或自定义界面，让复杂网络可以作为一个模块使用。" },
  button: { label: "按钮", description: "接收点击、按下或开关操作，常用于制作交互控制。" },
  null: { label: "空节点", description: "整理并稳定一条数据支路，常作为命名清晰的输出端。" },
  text: { label: "文本", description: "生成、显示或处理文字内容。" },
  select: { label: "选择引用", description: "从其他节点或通道中选择需要的数据。" },
  base: { label: "基础组件", description: "承载子网络、脚本或可复用功能模块。" },
  out: { label: "输出", description: "把当前网络的结果送到上一级网络。" },
  table: { label: "表格数据", description: "用行和列保存结构化文本或控制数据。" },
  math: { label: "数学运算", description: "缩放、偏移、合并或重新映射数值范围。" },
  in: { label: "输入", description: "接收上一级网络传入的数据。" },
  constant: { label: "常量", description: "生成固定颜色、固定数值或固定通道。" },
  ramp: { label: "渐变", description: "生成可编辑的颜色或数值渐变曲线。" },
  panelexec: { label: "面板事件", description: "监听鼠标、触摸和控件数值等面板交互事件。" },
  switch: { label: "切换", description: "在多个输入支路之间选择一个结果。" },
  parexec: { label: "参数事件", description: "监听参数变化并触发相应脚本。" },
  comp: { label: "组件引用", description: "引用、监控或处理组件层级中的对象。" },
  moviefilein: { label: "媒体文件输入", description: "读取图片、视频或图像序列。" },
  transform: { label: "变换", description: "调整位置、旋转、缩放或画面构图。" },
  eval: { label: "表达式求值", description: "计算表达式并输出得到的数据。" },
  par: { label: "参数引用", description: "读取其他节点的参数并转换成数据。" },
  cache: { label: "缓存", description: "保存一段历史数据，供延迟、回看或比较使用。" },
  datexec: { label: "数据事件", description: "监听 DAT 数据变化并执行脚本。" },
  noise: { label: "噪声", description: "生成随机但连续的纹理或数值变化。" },
  level: { label: "级别调整", description: "调整亮度、对比度、透明度或颜色范围。" },
  circle: { label: "圆形", description: "生成圆形图像、曲线或几何轮廓。" },
  merge: { label: "合并", description: "把多路数据、几何或通道汇合为一路。" },
  execute: { label: "执行事件", description: "在开始、结束或逐帧等时机执行脚本。" },
  over: { label: "图层叠加", description: "按照透明度把前景叠加到背景之上。" },
  annotate: { label: "网络注释", description: "为网络添加说明和功能分区，不参与实际计算。" },
  insert: { label: "插入", description: "向数据中插入新的行、列、样本或片段。" },
  opexec: { label: "节点事件", description: "监听节点状态变化并执行脚本。" },
  chopto: { label: "CHOP 转换", description: "把通道数据转换为其他数据形态。" },
  cacheselect: { label: "缓存选择", description: "从缓存数据中选择指定帧或片段。" },
  filein: { label: "文件输入", description: "从外部文件读取数据。" },
  analyze: { label: "分析", description: "计算平均值、最大值、最小值等统计结果。" },
  geo: { label: "几何组件", description: "承载三维几何体，并负责实例化和渲染设置。" },
  cam: { label: "摄像机", description: "决定三维场景的观察位置、方向和透视。" },
  light: { label: "灯光", description: "为三维场景提供照明、阴影和高光。" },
  filter: { label: "滤波", description: "平滑信号、削弱突变或提取特定频段。" },
  render: { label: "渲染", description: "把几何、材质、灯光和摄像机合成为最终图像。" },
  script: { label: "脚本处理", description: "通过 Python 或自定义逻辑生成和修改数据。" },
  fit: { label: "范围适配", description: "把输入数值从一个范围映射到另一个范围。" },
  limit: { label: "数值限制", description: "限制变化速度、上下边界或数值范围。" },
  line: { label: "线条", description: "生成线段、曲线或线性数据。" },
  lookup: { label: "查表映射", description: "使用渐变或查找表重新映射颜色与数值。" },
  panel: { label: "面板通道", description: "读取鼠标、触摸或组件面板的交互数据。" },
  widget: { label: "交互控件", description: "提供滑块、按钮等可操作的用户界面。" },
  web: { label: "网页", description: "加载网页内容或与 Web 数据进行交互。" },
  slider: { label: "滑块", description: "让用户连续调整一个数值。" },
  info: { label: "信息读取", description: "读取其他节点的状态、尺寸和运行信息。" },
  feedback: { label: "反馈", description: "把上一帧结果送回当前网络，形成拖影或循环效果。" },
  reorder: { label: "通道重排", description: "重新组合颜色或数据通道的顺序。" },
  grid: { label: "网格", description: "生成规则排列的点或线，常用于粒子实例位置。" },
  rectangle: { label: "矩形", description: "生成矩形图像、轮廓或几何形状。" },
  pattern: { label: "波形图案", description: "生成周期性波形或规则图案。" },
  topto: { label: "TOP 转 CHOP", description: "把图像像素转换成可运算的通道数据。" },
  sopto: { label: "SOP 转 CHOP", description: "把几何点的位置等属性转换成通道数据。" },
  trail: { label: "轨迹", description: "保存连续样本形成运动轨迹或历史曲线。" },
  blur: { label: "模糊", description: "柔化图像细节或扩散亮部。" },
  replicator: { label: "复制器", description: "根据表格或模板批量复制组件。" },
  express: { label: "表达式", description: "用表达式快速生成或修改通道。" },
  field: { label: "输入字段", description: "提供可输入文字或数值的界面控件。" },
  flip: { label: "翻转", description: "沿水平、垂直或时间方向翻转数据。" },
  lfo: { label: "低频振荡", description: "生成周期变化的控制信号。" },
  count: { label: "计数", description: "统计事件、样本或状态变化次数。" },
  audiodevin: { label: "音频设备输入", description: "从麦克风或声卡实时读取声音。" },
  res: { label: "分辨率", description: "调整图像宽高、像素数量和缩放方式。" },
  convert: { label: "格式转换", description: "转换数据类型、几何类型或像素格式。" },
  edge: { label: "边缘检测", description: "提取图像中亮度或颜色变化明显的边缘。" },
  add: { label: "相加合成", description: "把多路图像、数值或几何相加合并。" },
  logic: { label: "逻辑判断", description: "把连续数值转换成开关、条件或触发事件。" },
  moviefileout: { label: "媒体文件输出", description: "把画面录制为视频或图像序列。" },
  transpose: { label: "行列转置", description: "交换数据的行列方向。" },
  displace: { label: "位移扭曲", description: "使用另一幅图像或通道推动像素位置。" },
  opviewer: { label: "节点预览", description: "把指定节点的画面显示在组件中。" },
  multiply: { label: "相乘", description: "让两路图像或数值相乘，常用于遮罩和调制。" },
  cross: { label: "交叉混合", description: "在两路输入之间连续混合过渡。" },
  box: { label: "立方体", description: "生成盒状三维几何体。" },
  crop: { label: "裁剪", description: "截取图像或数据的指定区域。" },
  pointfilein: { label: "点文件输入", description: "读取外部点云或点位置数据。" },
  window: { label: "窗口函数", description: "使用窗口曲线衰减信号边缘。" },
  glsl: { label: "GLSL 着色器", description: "使用 GPU 着色器自定义图像或几何运算。" },
  videodevin: { label: "视频设备输入", description: "从摄像头或采集卡实时读取画面。" },
  rename: { label: "重命名", description: "修改通道、列或数据项的名称。" },
  shuffle: { label: "通道重组", description: "拆分、组合或重排图像和通道数据。" },
  sphere: { label: "球体", description: "生成球形三维几何体。" },
  fifo: { label: "先进先出缓存", description: "按时间顺序保存并推出历史样本。" },
  phong: { label: "Phong 材质", description: "为三维物体提供基础颜色、高光和光照反应。" },
  tube: { label: "管体", description: "沿曲线生成管状三维几何体。" },
  antialias: { label: "抗锯齿", description: "柔化图像边缘，减少像素锯齿。" },
  spring: { label: "弹簧平滑", description: "让数值产生带惯性和回弹的平滑变化。" },
  audiofilter: { label: "音频滤波", description: "保留或削弱指定频率范围的声音。" },
  glslmulti: { label: "多通道 GLSL", description: "通过 GLSL 同时处理多路输出。" },
  lag: { label: "延迟平滑", description: "减缓数值变化，降低抖动。" },
  slope: { label: "变化斜率", description: "计算信号随时间变化的速度。" },
  torus: { label: "圆环", description: "生成环形三维几何体。" },
  delete: { label: "删除", description: "删除指定点、面、行、列或样本。" },
  hsvadj: { label: "HSV 调整", description: "调整色相、饱和度和明度。" },
  parameter: { label: "参数控制", description: "读取或组织自定义参数。" },
  audiofilein: { label: "音频文件输入", description: "读取音频文件并输出声音通道。" },
  pbr: { label: "PBR 材质", description: "使用物理渲染方式控制金属度、粗糙度和反射。" },
  skin: { label: "蒙皮", description: "沿多条曲线生成连续曲面。" },
  copy: { label: "复制", description: "复制几何、图像或数据，并可由另一输入控制复制位置。" },
  keyboardin: { label: "键盘输入", description: "读取键盘按键状态并转换成控制通道。" },
  audiodevout: { label: "音频设备输出", description: "把声音发送到扬声器或指定声卡输出。" },
  chopexec: { label: "通道事件", description: "监听 CHOP 通道数值变化并触发 Python 脚本。" },
  mirror: { label: "镜像", description: "沿水平或垂直方向镜像图像或几何。" },
  resample: { label: "重新采样", description: "重新分配几何点或通道样本的数量与间距。" },
  attribcreate: { label: "创建属性", description: "为几何点、顶点或面创建自定义属性。" },
  environment: { label: "环境光材质", description: "使用环境贴图为三维物体提供反射和环境照明。" },
  pointfileselect: { label: "点文件选择", description: "从点文件输入中选择需要的点或属性。" },
  audiodyna: { label: "音频动态处理", description: "压缩或扩展声音的动态范围。" },
  audiospect: { label: "音频频谱", description: "把声音分解为不同频率的能量数据。" },
  substitute: { label: "替换数据", description: "按照匹配规则替换文字或表格内容。" },
  trigger: { label: "触发包络", description: "收到事件后生成带起伏过程的控制信号。" },
  substance: { label: "Substance 材质", description: "载入并控制 Substance 程序化材质。" },
  texture: { label: "纹理材质", description: "把图像纹理应用到三维物体表面。" },
  tile: { label: "平铺", description: "重复排列图像，形成连续纹理或图案。" },
  twist: { label: "扭转", description: "沿指定轴线扭曲三维几何。" },
  opview: { label: "节点视图", description: "显示指定节点的查看器画面。" },
  audiovst: { label: "VST 音频效果", description: "通过 VST 插件处理声音。" },
  matte: { label: "遮罩抠像", description: "根据透明度或颜色生成并调整遮罩。" },
  nvbackground: { label: "背景移除", description: "使用 NVIDIA 图像处理移除视频背景。" },
  scurve: { label: "S 形曲线", description: "用 S 形响应曲线重新塑造数值变化。" },
  blend: { label: "混合", description: "在多路数据或几何状态之间进行混合。" },
  importselect: { label: "导入选择", description: "从导入内容中选择指定部分继续处理。" },
  speed: { label: "速度", description: "计算通道随时间变化的速度或累积位移。" },
  normal: { label: "法线", description: "计算或调整三维几何表面的法线方向。" },
  monitors: { label: "显示器信息", description: "读取当前显示器的尺寸、位置和状态。" },
  mousein: { label: "鼠标输入", description: "读取鼠标位置、按键和滚轮状态。" },
  thresh: { label: "阈值", description: "按亮度或数值阈值把输入分成不同区域。" },
  replace: { label: "内容替换", description: "查找并替换数据中的指定内容。" },
  pointgenerator: { label: "点生成器", description: "在 GPU 上生成可继续运算的点，是 POP 点云和粒子网络常见的起点。" },
  particle: { label: "粒子", description: "根据速度、寿命和力场让点随时间运动，形成粒子系统。" },
  force: { label: "力场", description: "为点或粒子施加方向、吸引、排斥等运动力量。" },
};

const parameterChinese: Record<string, string> = {
  top: "顶部位置 / TOP 引用", bottomborder: "底部边框", align: "对齐方式", leftborder: "左边框", rightborder: "右边框", topborder: "顶部边框",
  autoexportroot: "自动导出根路径", dragscript: "拖拽脚本", clickthrough: "点击穿透", alignorder: "对齐顺序", dropscript: "放置脚本", opacity: "不透明度",
  rightanchor: "右侧锚点", aspect: "宽高比", defaultreadencoding: "默认读取编码", topsmoothness: "顶部平滑度", bgcolorg: "背景绿色", bgcolorb: "背景蓝色", bgcolorr: "背景红色", backcolorg: "背景绿色", backcolorb: "背景蓝色", backcolorr: "背景红色",
  buttongroup: "按钮组", cursor: "鼠标光标", vmode: "垂直模式", resolutionh: "分辨率高度", resolutionw: "分辨率宽度", bgalpha: "背景透明度", label: "标签", layer: "图层",
  dat: "DAT 数据源", text: "文本内容", fromop: "来源节点", rowindexend: "结束行索引", alignallow: "允许对齐", colindexend: "结束列索引", index: "索引", font: "字体",
  colexpr: "列筛选表达式", rowexpr: "行筛选表达式", file: "文件路径", outputresolution: "输出分辨率", op: "节点路径", fontcolorg: "字体绿色", fontcolorb: "字体蓝色", fontcolorr: "字体红色",
  rate: "速率", fontsize: "字号", spacing: "间距", operand: "运算对象", resmult: "分辨率倍数", tx: "X 轴位置", ty: "Y 轴位置", tz: "Z 轴位置", rx: "X 轴旋转", ry: "Y 轴旋转", rz: "Z 轴旋转",
  timeslice: "时间切片", enablecloning: "启用克隆", rows: "行数", builtin: "内置模式", bottomanchor: "底部锚点", filtertype: "滤波类型", fixedaspect: "固定宽高比", cols: "列数", inputfiltertype: "输入滤波类型",
  active: "启用状态", type: "类型", pars: "参数列表", renameto: "重命名为", extractrows: "提取行", panels: "面板列表", fontsizex: "横向字号", fillmode: "填充模式", extension: "扩展脚本", panelvalue: "面板数值",
  justifyv: "垂直对齐", justifyh: "水平对齐", timecodeop: "时间码节点", const0name: "常量 0 名称", const0value: "常量 0 数值", expr: "表达式", resizewmin: "最小宽度", resizehmin: "最小高度", resizewmax: "最大宽度", resizehmax: "最大高度",
  parameters: "参数集合", color1: "颜色 1", color2: "颜色 2", color3: "颜色 3", color4: "颜色 4", rowindexstart: "起始行索引", torange1: "输出范围起点", torange2: "输出范围终点", legacyfontselection: "旧版字体选择",
  fontautosize: "字体自动缩放", cachesize: "缓存大小", replaceindex: "替换索引", allowuishortcuts: "允许界面快捷键", colnames: "列名", rownames: "行名", gain: "增益", method: "处理方法", alignx: "横向对齐", linespacing: "行距",
  url: "网址", exporttable: "导出表格", legacyxform: "旧版变换", chop: "CHOP 数据源", interp: "插值方式", period: "周期", fillcolorb: "填充蓝色", fillcolorg: "填充绿色", fillcolorr: "填充红色", exportmethod: "导出方式",
  onpulse: "脉冲触发", callbacks: "回调脚本", phase: "相位", ops: "节点列表", px: "X 轴位置", py: "Y 轴位置", pz: "Z 轴位置", fontalpha: "字体透明度", sx: "X 轴缩放", sy: "Y 轴缩放", sz: "Z 轴缩放", enable: "启用", create: "创建方式",
  width: "宽度", height: "高度", size: "尺寸", scale: "缩放", offset: "偏移", speed: "速度", frequency: "频率", amplitude: "振幅", amp: "振幅", min: "最小值", max: "最大值", clamp: "限制范围", input: "输入", output: "输出", source: "来源", target: "目标", channel: "通道", name: "名称", path: "路径", alpha: "透明度", mode: "模式", fps: "帧率",
  brightness: "亮度", contrast: "对比度", gamma: "伽马", pivot: "中心基准", hue: "色相", saturation: "饱和度", blacklevel: "黑场", whitelevel: "白场",
  encloseops: "包含节点", layerzone: "图层区域", includeinorder: "纳入排列顺序", titletext: "标题文字", valuechange: "数值变化事件", outputaspect: "输出宽高比", crop: "裁剪方式",
  promoteextension1: "提升扩展 1", sizex: "X 轴尺寸", sizey: "Y 轴尺寸", destroy: "销毁事件", composite: "合成方式", replace: "替换方式", contents: "内容", bodymaxwidth: "正文最大宽度",
  channames: "通道名称", textpaddingb: "文字底部内边距", colorb: "蓝色分量", colorg: "绿色分量", colorr: "红色分量", extension1: "扩展 1", version: "版本", cachetop: "缓存 TOP",
  fromrange1: "输入范围起点", fromrange2: "输入范围终点", const1name: "常量 1 名称", const1value: "常量 1 数值", scope: "作用范围", rowchange: "行变化事件", tablechange: "表格变化事件",
  antialias: "抗锯齿", ontooff: "开关转换", marginb: "底部外边距", order: "排列顺序", palettecomp: "调色板组件", palettename: "调色板名称", radiusx: "X 轴半径", radiusy: "Y 轴半径",
  softnessoffset: "柔化偏移", combineinput: "合并输入",
};

const parameterTokenChinese: Record<string, string> = {
  custom: "自定义", input: "输入", output: "输出", source: "来源", target: "目标", color: "颜色", background: "背景", bg: "背景", font: "字体", fill: "填充", border: "边框", left: "左", right: "右", top: "上", bottom: "下",
  width: "宽度", height: "高度", size: "尺寸", scale: "缩放", offset: "偏移", speed: "速度", frequency: "频率", amplitude: "振幅", phase: "相位", range: "范围", minimum: "最小", maximum: "最大", min: "最小", max: "最大",
  row: "行", rows: "行数", column: "列", columns: "列数", col: "列", index: "索引", start: "起点", end: "终点", value: "数值", name: "名称", path: "路径", file: "文件", folder: "文件夹", channel: "通道", resolution: "分辨率", rate: "速率", time: "时间", frame: "帧", mode: "模式", type: "类型", enable: "启用", active: "激活", export: "导出", import: "导入", script: "脚本", callback: "回调", callbacks: "回调", alpha: "透明度", opacity: "不透明度", gain: "增益", period: "周期",
};

export function touchDesignerOperatorChinese(operatorType: string, family: TouchDesignerFamily): OperatorGlossary {
  const key = normalizeKey(operatorType);
  return operatorGlossary[key] ?? {
    label: `${touchDesignerFamilyChinese[family]}节点`,
    description: `用于当前网络中的${touchDesignerFamilyChinese[family]}数据处理；保留英文类型 ${operatorType || "unknown"}，方便回到 TouchDesigner 中查找。`,
  };
}

export function touchDesignerParameterChinese(parameterName: string) {
  const key = normalizeKey(parameterName);
  if (parameterChinese[key]) return parameterChinese[key];
  const tokens = splitParameterName(parameterName);
  if (tokens.length && tokens.every((token) => parameterTokenChinese[token])) return tokens.map((token) => parameterTokenChinese[token]).join("");
  return "节点参数";
}

function normalizeKey(value: string) {
  return value.trim().toLowerCase().replace(/[\s_-]+/g, "");
}

function splitParameterName(value: string) {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase().split(/[\s_-]+/).filter(Boolean);
}
